# Generated by Django 4.0.4 on 2022-04-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticias',
            new_name='Noticia',
        ),
    ]
