# Generated by Django 4.0.4 on 2022-04-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_rename_noticias_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='pag_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
